repos:
- repo: local
  hooks:
    - id: int-flake8-src
      name: lint-flake8-src
      entry: poetry
      args: [run, flake8, --config, pyproject.toml, ./src]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: int-flake8-tests
      name: lint-flake8-tests
      entry: poetry
      args: [run, flake8, --config, pyproject.toml, ./tests]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: int-mypy-src
      name: lint-mypy-src
      entry: poetry
      args: [run, mypy, --config-file, pyproject.toml, src]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: int-mypy-tests
      name: lint-mypy-tests
      entry: poetry
      args: [run, mypy, --config-file, pyproject.toml, tests]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: int-pylint-src
      name: lint-pylint-src
      entry: poetry
      args: [run, pylint, --rcfile, pyproject.toml, src]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: int-pylint-tests
      name: lint-pylint-tests
      entry: poetry
      args: [run, pylint, --rcfile, pyproject.toml, tests]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: test-cov
      name: test-cov
      entry: poetry
      args: [run, pytest, --cov=src/app, --cov-report, term]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: sec-trivy-sca
      name: sec-trivy-sca
      entry: trivy
      args: [fs,  --exit-code, "1", --scanners, vuln, .]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: sec-trivy-iast
      name: sec-trivy-iast
      entry: trivy
      args: [fs,  --exit-code, "1", --scanners, config, .]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: sec-trivy-secrets
      name: sec-trivy-secrets
      entry: trivy
      args: [fs, --exit-code, "1", --scanners, secret, .]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true
    - id: sec-sast-bandit
      name: sec-test-cov
      entry: poetry
      args: [run, bandit, -c, pyproject.toml, -r, src]
      language: system
      always_run: true
      pass_filenames: false
      verbose: true