repos:
- repo: local
  hooks:
    - id: hook
      name: hook-test
      entry: pwd
      language: system
      always_run: true
      pass_filenames: false
      fail_fast: true
      verbose: true
    # - id: lint
    #   name: lint
    #   entry: make
    #   args: [lint]
    #   language: system
    #   always_run: true
    #   pass_filenames: false
    #   fail_fast: true
    # - id: test-cov
    #   name: test-cov
    #   entry: make test-cov
    #   language: system
    #   always_run: true
    #   pass_filenames: false