repo_name: My-Python-Template
repo_url: https://github.com/brunobotelhobr/My-Python-Template
site_author: Bruno Botelho <bruno.botelho.br@gmail.com>
site_description: ''
edit_uri: /docs
site_name: app
site_url: ''
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

watch:
  - src

markdown_extensions:
  - attr_list

plugins:
  - mkdocstrings:

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Install: install.md
  - Manual: manual.md
  - FAQ: faq.md
  - How to Contribute: how-to-guides.md
  - Code: code.md

extra:
  version:
    provider: mike